// @ts-ignore `.open-next/worker.js` is generated by the Cloudflare build.
import { default as handler } from './.open-next/worker.js';

export { JevLiveLedger } from './lib/live-ledger-do';

export default {
  fetch: handler.fetch,
};
