'use client';
import { useEffect, useMemo, useState } from 'react';
import type { PlaygroundInput, PlaygroundQuestionType, PlaygroundResult } from '../../lib/playground';

const examples: Record<string, PlaygroundInput & { title: string; description: string }> = {
  expense: { title: '経費をどう扱う？', description: '状態を渡すと、決めた選択肢のどれに近いかを判定します。', state: { merchant: 'Acme Cloud', amount: 12800, memo: 'チーム用のクラウド利用料', recurring: true }, question: { id: 'category', type: 'choice', instructions: '取引の状態だけを見て、最も適切な分類を1つ選んでください。', criteria: { expense: '経費', review: '要確認', personal: '私用の可能性' } } },
  incident: { title: '障害の緊急度は？', description: '同じ状態でも、基準を変えると判断の問いが変わります。', state: { service: 'checkout', affectedUsers: 420, startedMinutesAgo: 18, paymentFailures: true }, question: { id: 'urgency', type: 'score', instructions: '影響の大きさと安全性を基準に、緊急度を順序づけてください。', criteria: ['低: 影響なし', '中: 一部ユーザー', '高: 決済や安全に影響'] } },
};

export default function Playground() {
  const [example, setExample] = useState('expense');
  const [stateText, setStateText] = useState(JSON.stringify(examples.expense.state, null, 2));
  const [type, setType] = useState<PlaygroundQuestionType>('choice');
  const [questionId, setQuestionId] = useState('category');
  const [instructions, setInstructions] = useState(examples.expense.question.instructions);
  const [criteriaText, setCriteriaText] = useState(JSON.stringify(examples.expense.question.criteria, null, 2));
  const [mode, setMode] = useState<'replay' | 'rule' | 'jev'>('replay');
  const [result, setResult] = useState<PlaygroundResult | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [controller, setController] = useState<AbortController | null>(null);
  const [comparison, setComparison] = useState<Record<string, PlaygroundResult>>({});
  useEffect(() => { try { const saved = localStorage.getItem('jev-playground-comparison'); if (saved) setComparison(JSON.parse(saved)); } catch { /* local-only history is best effort */ } }, []);
  useEffect(() => { try { localStorage.setItem('jev-playground-comparison', JSON.stringify(comparison)); } catch { /* storage may be disabled */ } }, [comparison]);
  const input = useMemo<PlaygroundInput | null>(() => { try { const state = JSON.parse(stateText); const criteria = type === 'noul' ? undefined : JSON.parse(criteriaText); return { state, question: { id: questionId, type, instructions, ...(criteria !== undefined ? { criteria } : {}) } }; } catch { return null; } }, [stateText, criteriaText, type, questionId, instructions]);
  const preview = input ? JSON.stringify({ model: 'typesafe/jev-latest', state: input.state, questions: { [questionId]: { instructions, type, ...(input.question.criteria !== undefined ? { criteria: input.question.criteria } : {}) } } }, null, 2) : 'JSONを修正するとプレビューできます。';
  const loadExample = (key: string) => { const e = examples[key]; setExample(key); setStateText(JSON.stringify(e.state, null, 2)); setType(e.question.type); setQuestionId(e.question.id); setInstructions(e.question.instructions); setCriteriaText(JSON.stringify(e.question.criteria ?? {}, null, 2)); setResult(null); setError(''); };
  const run = async () => {
    setError(''); setResult(null); if (!input || !input.state || Array.isArray(input.state)) { setError('state はJSONオブジェクトで入力してください。'); return; }
    setLoading(true);
    if (mode !== 'jev') { const answer = type === 'choice' ? { id: questionId, type: 'choice' as const, choice: Object.keys((input.question.criteria ?? {}) as object)[0] } : type === 'score' ? { id: questionId, type: 'score' as const, score: 0 } : { id: questionId, type: 'noul' as const, noul: null }; const next = { runId: `${mode}_${Date.now()}`, provider: mode, model: mode === 'replay' ? 'replay-v1' : 'rule-v1', durationMs: 0, answer, usage: { status: 'unavailable' as const }, cost: { status: 'unavailable' as const }, priceBasisVersion: 'unavailable' }; setResult(next); setComparison(c => ({ ...c, [mode]: next })); setLoading(false); return; }
    const c = new AbortController(); setController(c);
    try { const r = await fetch('/api/playground', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input), signal: c.signal }); const body = await r.json(); if (!r.ok) throw new Error(body.error ?? '実行できませんでした。'); setResult(body); setComparison(x => ({ ...x, jev: body })); } catch (e) { if ((e as Error).name !== 'AbortError') setError((e as Error).message); } finally { setController(null); setLoading(false); }
  };
  return <div className="playground"><section className="pg-hero"><div className="eyebrow">JEV PLAYGROUND</div><h1>判断AIを、触って理解する。</h1><p>Jevはチャットで答えを生成するものではありません。あなたが渡した状態（state）を、型付きの問い（questions）に照らして判定します。</p><div className="notice"><strong>大事なこと：</strong>確率やconfidenceは真実・承認ではありません。隠れた思考過程や、存在しない根拠を表示・捏造しません。</div></section>
    <div className="pg-grid"><section className="panel pg-editor"><div className="section-title"><h2>1. 状態と問いをつくる</h2><span className="count">編集可能</span></div><div className="example-tabs" role="tablist">{Object.entries(examples).map(([key, e]) => <button key={key} className={`chip ${example === key ? 'active' : ''}`} onClick={() => loadExample(key)}>{e.title}</button>)}</div><label>状態 JSON <textarea value={stateText} onChange={e => setStateText(e.target.value)} rows={9} spellCheck={false} /></label><label>質問ID <input value={questionId} onChange={e => setQuestionId(e.target.value)} /></label><label>instructions <textarea value={instructions} onChange={e => setInstructions(e.target.value)} rows={3} /></label><label>問いの型 <select value={type} onChange={e => setType(e.target.value as PlaygroundQuestionType)}><option value="choice">Choice — 選択肢</option><option value="score">Score — 順序・点数</option><option value="noul">Noul — 該当度なし/あり</option></select></label>{type !== 'noul' && <label>{type === 'choice' ? 'criteria マップ JSON' : 'criteria 配列 JSON'}<textarea value={criteriaText} onChange={e => setCriteriaText(e.target.value)} rows={5} spellCheck={false} /></label>}<div className="mode-row"><span>実行モード</span>{(['replay', 'rule', 'jev'] as const).map(m => <button key={m} className={`chip ${mode === m ? 'active' : ''}`} onClick={() => setMode(m)}>{m === 'jev' ? 'Jev live' : m === 'replay' ? 'Replay' : 'Rule baseline'}</button>)}</div><div className="actions"><button className="primary" onClick={run} disabled={loading}>{loading ? '判定中…' : '判定を実行'}</button>{loading && <button className="secondary" onClick={() => controller?.abort()}>キャンセル</button>}</div>{error && <div className="error" role="alert">{error}</div>}</section>
      <aside className="pg-side"><section className="panel"><h2>2. Tachyonへ送る形</h2><p className="muted">Jev liveではこのJSONをサーバーから送ります。</p><pre className="request-preview">{preview}</pre><div className="explain"><b>Choice</b><span>候補のどれかを選ぶ</span><b>Score</b><span>順序づけられた基準で点をつける</span><b>Noul</b><span>問いへの該当度を返す</span></div></section><section className="panel"><h2>3. 判定結果</h2>{result ? <ResultView result={result} criteria={input?.question.criteria} /> : <p className="muted">実行すると、型付きの結果がここに表示されます。結果は意思決定・承認そのものではありません。</p>}{Object.keys(comparison).length > 0 && <div className="comparison"><h3>同じ入力の比較</h3>{(['replay','rule','jev'] as const).map(k => <div key={k}><span>{k === 'jev' ? 'Jev live（実測）' : k === 'replay' ? 'Replay（固定）' : 'Rule（決定的）'}</span><b>{comparison[k] ? (comparison[k].answer.choice ?? comparison[k].answer.score ?? comparison[k].answer.noul ?? 'N/A') : '—'}</b></div>)}</div>}</section></aside></div><div className="data-note">入力データはこの画面の実行にのみ使われます。Replay / Rule は外部APIへ送信しません。Jev liveはサーバー側の設定済みTachyon APIへ送信され、ブラウザにトークンは渡りません。</div></div>;
}

  function ResultView({ result, criteria }: { result: PlaygroundResult; criteria?: PlaygroundInput['question']['criteria'] }) { const a = result.answer; return <div className="result"><div className="result-badge">{result.provider === 'jev' ? 'Jev live' : result.provider === 'replay' ? 'Replay' : 'Rule baseline'}</div><div className="answer-main">{a.type === 'choice' ? <><small>選択された候補</small><strong>{a.choice}</strong></> : a.type === 'score' ? <><small>スコア</small><strong>{a.score}</strong></> : <><small>該当度</small><strong>{a.noul === null ? 'N/A' : a.noul}</strong></>}</div>{a.legend && <p className="muted">legend: {JSON.stringify(a.legend)}</p>}{a.probabilities && <div className="probabilities">{Object.entries(a.probabilities).map(([k, v]) => <div key={k}><span>{k}</span><div><i style={{ width: `${Math.round(v * 100)}%` }} /></div><b>{Math.round(v * 100)}%</b></div>)}</div>}<dl className="meta"><div><dt>model</dt><dd>{result.model}</dd></div><div><dt>duration</dt><dd>{result.durationMs} ms</dd></div><div><dt>usage / cost</dt><dd>{'status' in result.usage ? 'unavailable' : `${result.usage.input_tokens} + ${result.usage.output_tokens} tokens`} / {'status' in result.cost ? 'unavailable' : result.cost.cost_nanodollars}</dd></div></dl>{a.confidence !== undefined && <p className="muted">confidence: {Math.round(a.confidence * 100)}%（真実度ではありません）</p>}</div>; }
