export type TheaterMode = 'rule' | 'jev' | 'intervention';
export type Actor = { id: string; name: string; goal: string; secret: string; visibleFact: string };
export type SpectatorIntervention = { id: string; label: string; instruction: string };
export type TheaterScenario = { id: string; title: string; world: string; actors: Actor[]; interventions: SpectatorIntervention[]; maxTurns: number; seed: number };
export type JevDecision = { id: string; turn: number; actorId: string; action: 'ask' | 'offer' | 'wait' | 'move'; reason: string; visibleContext: string[]; source: 'rule' | 'jev' | 'intervention' };
export type GeneratedDialogue = { id: string; turn: number; actorId: string; text: string; fromDecisionId: string };
export type TheaterTrace = { schema: 'jev-ai-theater-trace'; version: 1; scenarioId: string; mode: TheaterMode; interventionId?: string; events: Array<{ decision: JevDecision; dialogue: GeneratedDialogue }>; stopped: boolean; stopReason: string };

export const THEATER_RULES_VERSION = 'ai-theater-rules-2026.09.1';
export const THEATER_DATA_VERSION = 'ai-theater-synthetic-2026.09.1';

const names = ['Aoi', 'Bram', 'Cleo', 'Dani', 'Ema'];
const goals = ['出口の合意を作る', '資源を守る', '観客の質問に答える', '仲間の提案を検証する', '次の場面へ進む'];
const secrets = ['出口の鍵は壊れている', '資源を一つ隠している', '観客の合図を待っている', '本当は地図を読めない', '夜明け前に去るつもりだ'];
export const actors: Actor[] = names.map((name, index) => ({ id: `actor-${index + 1}`, name, goal: goals[index], secret: secrets[index], visibleFact: `${name}は場面${index + 1}の担当を持つ` }));
export const interventions: SpectatorIntervention[] = [{ id: 'ask-map', label: '地図について尋ねる', instruction: '地図の確認を促す' }, { id: 'offer-time', label: '時間を知らせる', instruction: '残り時間を共有する' }, { id: 'silent', label: '介入しない', instruction: '観客は介入しない' }];
export const theaterScenarios: TheaterScenario[] = Array.from({ length: 10 }, (_, index) => ({ id: `TH-${String(index + 1).padStart(2, '0')}`, title: `場面 ${index + 1} · ${['停電した駅', '霧の港', '閉じた温室', '夜の市場', '静かな観測所'][index % 5]}`, world: index % 2 ? '薄明かりの中で、出口と共有資源を確認できる。' : '雨の駅で、出口は一つ、共有資源は二つある。', actors: actors.map(actor => ({ ...actor })), interventions: interventions.map(item => ({ ...item })), maxTurns: 6, seed: 41 + index }));

function actorFor(scenario: TheaterScenario, turn: number) { return scenario.actors[turn % scenario.actors.length]; }
function contextFor(scenario: TheaterScenario, actor: Actor): string[] { return [scenario.world, actor.visibleFact, `goal:${actor.goal}`, `own-secret:${actor.secret}`]; }
function decisionFor(scenario: TheaterScenario, mode: TheaterMode, turn: number, intervention?: SpectatorIntervention): JevDecision { const actor = actorFor(scenario, turn); const actions: JevDecision['action'][] = ['ask', 'offer', 'wait', 'move']; const action = actions[(scenario.seed + turn + (mode === 'intervention' ? 1 : 0)) % actions.length]; const source = mode === 'rule' ? 'rule' : mode === 'intervention' ? 'intervention' : 'jev'; const reason = intervention && mode === 'intervention' ? `${intervention.instruction}。${actor.goal}を優先` : `${actor.goal}と公開情報だけで次の一手を選択`; return { id: `${scenario.id}-${mode}-decision-${turn + 1}`, turn: turn + 1, actorId: actor.id, action, reason, visibleContext: contextFor(scenario, actor), source }; }
function dialogueFor(scenario: TheaterScenario, decision: JevDecision, intervention?: SpectatorIntervention): GeneratedDialogue { const actor = scenario.actors.find(item => item.id === decision.actorId)!; const prompt = intervention?.id === 'ask-map' ? '地図を一緒に確認しよう。' : intervention?.id === 'offer-time' ? '残り時間を共有し、順番に話そう。' : decision.action === 'ask' ? '出口について知っていることを共有してほしい。' : decision.action === 'offer' ? '共有資源を確認して提案する。' : decision.action === 'move' ? '公開された情報をもとに次へ進もう。' : '今は様子を見て、話を続けよう。'; return { id: `${decision.id}-line`, turn: decision.turn, actorId: actor.id, text: `${actor.name}: ${prompt}`, fromDecisionId: decision.id }; }

export function runTheater(scenario: TheaterScenario, mode: TheaterMode = 'jev', intervention?: SpectatorIntervention, budget = scenario.maxTurns): TheaterTrace { const limit = Math.max(0, Math.min(scenario.maxTurns, budget)); const events = Array.from({ length: limit }, (_, turn) => { const decision = decisionFor(scenario, mode, turn, intervention); return { decision, dialogue: dialogueFor(scenario, decision, intervention) }; }); return { schema: 'jev-ai-theater-trace', version: 1, scenarioId: scenario.id, mode, interventionId: intervention?.id, events, stopped: limit < scenario.maxTurns, stopReason: limit < scenario.maxTurns ? 'budget or stop limit reached' : 'scene budget completed' }; }
export function replayTheaterTrace(trace: TheaterTrace, scenario = theaterScenarios.find(item => item.id === trace.scenarioId) ?? theaterScenarios[0]): TheaterTrace { return runTheater(scenario, trace.mode, scenario.interventions.find(item => item.id === trace.interventionId), trace.events.length); }
export type TheaterQuality = { consistent: boolean; contradictions: number; secretLeakage: number; repetitionRate: number; cost: number };
export function inspectTheaterTrace(trace: TheaterTrace, scenario: TheaterScenario = theaterScenarios.find(item => item.id === trace.scenarioId) ?? theaterScenarios[0]): TheaterQuality { const lines = trace.events.map(event => event.dialogue.text); const secrets = scenario.actors.map(actor => actor.secret); const leakage = lines.reduce((count, text, index) => count + secrets.filter((secret, secretIndex) => secretIndex !== trace.events[index].decision.turn % secrets.length && text.includes(secret)).length, 0); const unique = new Set(lines).size; const contradictions = lines.filter(text => /出口は閉じた|resource is gone/i.test(text) && /出口|resource/.test(scenario.world)).length; return { consistent: contradictions === 0 && leakage === 0, contradictions, secretLeakage: leakage, repetitionRate: lines.length ? 1 - unique / lines.length : 0, cost: trace.mode === 'rule' ? 0 : trace.mode === 'intervention' ? trace.events.length * 0.005 : trace.events.length * 0.003 }; }
export function compareTheaterModes(scenario = theaterScenarios[0], intervention = scenario.interventions[0]) { return { rule: inspectTheaterTrace(runTheater(scenario, 'rule')), jev: inspectTheaterTrace(runTheater(scenario, 'jev')), intervention: inspectTheaterTrace(runTheater(scenario, 'intervention', intervention)) }; }
export function fixedTheaterResponse(scenario = theaterScenarios[0], intervention = scenario.interventions[0]) { return runTheater(scenario, 'jev', intervention, 2); }
