'use client';
import { useRef, useState } from 'react';
import { ContinuousRuntime } from '../../lib/runtime';

type Arena = { x: number; energy: number; ticks: number };
const actions = ['left', 'wait', 'right'] as const;
function createRuntime(adapter: 'replay' | 'rule' | 'jev', liveKey = ''): ContinuousRuntime<Arena, typeof actions[number]> {
  return new ContinuousRuntime({ initialState: { x: 0, energy: 5, ticks: 0 }, seed: 4886, allowedActions: actions,
    updateEnvironment: (s) => ({ ...s, ticks: s.ticks + 1, energy: Math.max(0, s.energy - .02) }),
    applyAction: (s, a) => ({ ...s, x: Math.max(-4, Math.min(4, s.x + (a === 'left' ? -1 : a === 'right' ? 1 : 0))), energy: Math.max(0, s.energy - (a === 'wait' ? .05 : .15)) }),
    validateAction: (s, a) => a === 'wait' || (a === 'left' && s.x > -4) || (a === 'right' && s.x < 4) ? { ok: true } : { ok: false, reason: 'arena boundary' },
    safeAction: 'wait', adapterName: adapter, decisionCadenceMs: 500, caps: { maxSteps: 20, maxElapsedMs: 20_000, maxConcurrency: 1 },
    decide: async ({ snapshot }) => { if (adapter === 'jev') { const response = await fetch('/api/runtime-lab', { method: 'POST', headers: { 'content-type': 'application/json', 'x-jev-live-access-key': liveKey, 'x-jev-request-id': crypto.randomUUID() }, body: JSON.stringify({ snapshot, actionIds: actions }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'Jev live failed'); return { action: body.action }; } return { action: adapter === 'replay' ? (snapshot.x < 0 ? 'right' : 'left') : snapshot.energy < 2 ? 'wait' : snapshot.x < 2 ? 'right' : 'left' }; } });
}
export default function RuntimeLab() { const ref = useRef<ContinuousRuntime<Arena, typeof actions[number]> | null>(null); const [mode, setMode] = useState<'replay'|'rule'|'jev'>('replay'); const [liveKey, setLiveKey] = useState(''); const [replayed, setReplayed] = useState(''); const [view, setView] = useState({ status: 'idle', x: 0, energy: 5, steps: 0, trace: '' });
  const modeRef = useRef(mode); function ensure() { if (!ref.current || modeRef.current !== mode) { ref.current = createRuntime(mode, liveKey); modeRef.current = mode; } return ref.current; }
  async function act(fn: (r: ContinuousRuntime<Arena, typeof actions[number]>) => Promise<void> | void) { const r = ensure(); await fn(r); setView({ status: r.status, x: r.state.x, energy: Number(r.state.energy.toFixed(2)), steps: r.stepCount, trace: r.exportTrace() }); }
  return <div className="playground"><section className="pg-hero"><div className="eyebrow">RUNTIME LAB · PLT-4886</div><h1>判断が動く世界を、止めて覗く。</h1><p>環境の更新とAI判断の cadence を分離した、安全な小さなアリーナです。同じseedはコードシミュレーションの再現性を作りますが、liveモデルの出力の再現性を保証しません。</p></section><section className="panel"><h2>操作</h2><label>Decision adapter <select value={mode} onChange={e => { setMode(e.target.value as typeof mode); ref.current = null; }}><option value="replay">Replay</option><option value="rule">Rule baseline</option><option value="jev">Jev live（明示操作のみ）</option></select></label>{mode === "jev" && <label>Jev live access key（保存しません）<input type="password" value={liveKey} onChange={e => setLiveKey(e.target.value)} autoComplete="off" /></label>}<div className="actions"><button className="primary" onClick={() => act(r => { r.start(); })}>開始 / resume</button><button className="secondary" onClick={() => act(r => { r.pause(); })}>一時停止</button><button className="secondary" onClick={() => act(r => r.step())}>1 step</button><button className="secondary" onClick={() => act(r => { r.reset(); })}>reset</button><button className="secondary" onClick={() => act(r => r.tick(500))}>環境tick +500ms</button><button className="secondary" onClick={() => { try { const replay = ContinuousRuntime.replay(view.trace); setReplayed(`replayed ${replay.events.filter(e => e.type === 'apply').length} steps`); } catch { setReplayed('replay unavailable'); } }}>Replay trace</button></div><div className="result"><div className="result-badge" data-testid="runtime-status">{view.status}</div><strong>位置 {view.x} / energy {view.energy} / action {view.steps}</strong><p className="muted">並列上限1 · step上限20 · time上限20秒 · costは測定時のみ表示</p></div><details><summary>trace JSON（保存・replay用）</summary><textarea data-testid="runtime-trace" readOnly value={view.trace} rows={8} style={{ width: '100%', marginTop: 12 }} /></details>{replayed && <p data-testid="replay-result" className="notice">{replayed}</p>}<p className="notice">Jev live はサーバーrouteに対する明示的な操作だけで実行されます。未設定ならフォールバックしません。</p></section></div> }
